#baseURL = "http://example.org/"
#languageCode = "en-us"
#title = "My New Hugo Site"
#######################################
baseURL = "/"
title = "DevOps Learning"
author = "Badrish Mishra"
copyright = "Copyright © 2008–2020, BadrishMishra all rights reserved."
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

theme = "casper"

[params]
  facebook = "https://facebook.com/badrish.mishra.5"
  twitter = "https://twitter.com/bamishr"
  github = "https://github.com/bamishr"
  description = "MyBlog For Learning DevOps Latest!!"
  mainSections = ["post"]
  cover = "lion2.jpg"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "image-credit"
    name = "Image Credit"
    url = "/image-credit/"
    weight = 20
  [[menu.main]]
    identifier = "github-repo-theme"
    name = "Get Theme on Github"
    url = "https://github.com/jonathanjanssens/hugo-casper3"
    weight = 30
  [[menu.main]]
    identifier = "author"
    name = "Author Homepage"
    url = "https://bamishr.github.io/"
    weight = 40

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
